[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rng = "0.1.0"
sha3 = "0.10.7"
uuid = { version = "1.3.1", features = ["v4"] }

